pipeline {
    agent any
    environment {
        //define your vars
        NAME = 'Toro'
    }

    stages {

        stage('Build docker images') {
            steps {
                // Building stage
                echo "Welcome to ${NAME} Jenkins World"
                sh '''
                docker build . -t kennytoro/weatherapp
                '''
                echo " The Build Url is ${BUILD_URL}"
            }
        }

        stage('Push Docker Image to Toro repo') {
            steps {
                sh '''
                docker push kennytoro/weatherapp
                '''
            }
        }

        stage('Test') {
            steps {
                sh "docker images"
            }
        }
        stage('Running the image on k8s cluster') {
            steps {
                sh " kubectl apply -f ./deployment/"
            }
        }
        stage('Confirm Deployment is running') {
            steps {
                sh " kubectl get po -w"
                sh " kubectl get deployment"
            }
        }
    }

    post {
        success {
            // Actions to be perform when the pipeline is successful
            echo " T for Thanks... Man good job on ${BUILD_ID} build"
        }
        failure {
            echo "Pipeline failed... Ooops man down"
        }
    }
}