pipeline {
    agent any
    environment {
        //define your vars
        NAME = 'Toro'
    }
    triggers {
        pollSCM '* * * * *'
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone of the repos
                git 'https://github.com/kennytoro/health_check.git'
            }
        }

        stage('Build') {
            steps {
                // Building stage
                echo "Welcome to ${NAME} Jenkins World"
                sh '''
                docker build . -t kennytoro/weatherapp
                docker images
                '''
                echo " The Build Url is ${BUILD_URL}"
            }
        }

        stage('Deploy') {
            steps {
                // This is the deploy stage
                sh '''
                docker push kennytoro/weatherapp
                '''
                
            }
        }

        stage('Test') {
            steps {
                sh "docker images"
            }
        }
    }

    post {
        success {
            // Actions to be perform when the pipeline is successful
            echo " T for Thanks... Man go job on ${BUILD_ID} build"
        }
        failure {
            echo "Pipeline failed... Ooops man down"
        }
    }
}